[package]
name = "rust_alter_table"
version = "0.1.0"
authors = ["marcelolecar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
clokwerk = "0.3.3"
log = "0.4"
simple_logger = "1.4.0"
mysql = "*"
