version: '2'
services:
    mysqldb-test-alter-table:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_password
            MYSQL_ROOT_PASSWORD: master
        ports:
            - 3306:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init/000-structure.sql:/docker-entrypoint-initdb.d/000-structure.sql
volumes:
    mysql-data: